### ISSUE TITLE
뮤즈캣 베타의 프로젝트 기여에 관하여

### ISSUE THREAD

**Issue by 4rNe5** [ericbaek/musefinder#1]
안녕하세요!! 뮤즈캣 잘 쓰고있는 흔한 개발자입니다^^
이번 뮤즈캣 Beta 프로젝트에 기여를 하고싶은데, 혹시 Repo 링크나
기여하는 방법을 알려주실 수 있나요?
긍정적인 답변 기대하겠습니다!!

**Comment by ericbaek** [comment]
안녕하세요! 뮤즈캣에서 메인 개발자로써 참여중인 에릭이라고 합니다.
뮤즈캣 베타에 들어간 Feedback를 통해서 이메일을 전달해주시면 자세한 내용을 논의해볼 수 있을 것 같습니다.
여담으로, Musefinder는 musecat의 프로젝트 명으로 개발중일때 잠시 Public으로 돌린 것이고, 현재는 오픈소스로 운영할 생각은 없습니다. (내부 인원들의 동의도 받아야하고 저 혼자 운영하는 프로젝트도 아닌지라;;)

**Comment by 4rNe5** [comment]
감사합니다!! feedback을 통해 이메일 남겨두었습니다!
